version: '3.7'
services:
    jupyter:
        build:
            context: .
            dockerfile: deployment/jupyter.Dockerfile
        ports:
          - "3100:3100"
        volumes:
          - .:/app
        command: "-m jupyter notebook . --ip=0.0.0.0 --port=3100 --allow-root --NotebookApp.token='' --NotebookApp.password=''"
